// Code generated by go-swagger; DO NOT EDIT.

package uploader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/uploader/models"
)

// GetUploaderFilesServeIDHandlerFunc turns a function with the right signature into a get uploader files serve ID handler
type GetUploaderFilesServeIDHandlerFunc func(GetUploaderFilesServeIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUploaderFilesServeIDHandlerFunc) Handle(params GetUploaderFilesServeIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetUploaderFilesServeIDHandler interface for that can handle valid get uploader files serve ID params
type GetUploaderFilesServeIDHandler interface {
	Handle(GetUploaderFilesServeIDParams, *models.Principal) middleware.Responder
}

// NewGetUploaderFilesServeID creates a new http.Handler for the get uploader files serve ID operation
func NewGetUploaderFilesServeID(ctx *middleware.Context, handler GetUploaderFilesServeIDHandler) *GetUploaderFilesServeID {
	return &GetUploaderFilesServeID{Context: ctx, Handler: handler}
}

/*
	GetUploaderFilesServeID swagger:route GET /uploader/files/serve/{id} uploader getUploaderFilesServeId

get raw file version
*/
type GetUploaderFilesServeID struct {
	Context *middleware.Context
	Handler GetUploaderFilesServeIDHandler
}

func (o *GetUploaderFilesServeID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUploaderFilesServeIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
