// Code generated by go-swagger; DO NOT EDIT.

package uploader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ole-larsen/uploader/models"
)

// GetUploaderFilesServeIDOKCode is the HTTP code returned for type GetUploaderFilesServeIDOK
const GetUploaderFilesServeIDOKCode int = 200

/*
GetUploaderFilesServeIDOK file

swagger:response getUploaderFilesServeIdOK
*/
type GetUploaderFilesServeIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.File `json:"body,omitempty"`
}

// NewGetUploaderFilesServeIDOK creates GetUploaderFilesServeIDOK with default headers values
func NewGetUploaderFilesServeIDOK() *GetUploaderFilesServeIDOK {

	return &GetUploaderFilesServeIDOK{}
}

// WithPayload adds the payload to the get uploader files serve Id o k response
func (o *GetUploaderFilesServeIDOK) WithPayload(payload *models.File) *GetUploaderFilesServeIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get uploader files serve Id o k response
func (o *GetUploaderFilesServeIDOK) SetPayload(payload *models.File) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUploaderFilesServeIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUploaderFilesServeIDInternalServerErrorCode is the HTTP code returned for type GetUploaderFilesServeIDInternalServerError
const GetUploaderFilesServeIDInternalServerErrorCode int = 500

/*
GetUploaderFilesServeIDInternalServerError When some error occurs

swagger:response getUploaderFilesServeIdInternalServerError
*/
type GetUploaderFilesServeIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUploaderFilesServeIDInternalServerError creates GetUploaderFilesServeIDInternalServerError with default headers values
func NewGetUploaderFilesServeIDInternalServerError() *GetUploaderFilesServeIDInternalServerError {

	return &GetUploaderFilesServeIDInternalServerError{}
}

// WithPayload adds the payload to the get uploader files serve Id internal server error response
func (o *GetUploaderFilesServeIDInternalServerError) WithPayload(payload *models.Error) *GetUploaderFilesServeIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get uploader files serve Id internal server error response
func (o *GetUploaderFilesServeIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUploaderFilesServeIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
