// Code generated by go-swagger; DO NOT EDIT.

package uploader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/uploader/models"
)

// PostUploaderFilesHandlerFunc turns a function with the right signature into a post uploader files handler
type PostUploaderFilesHandlerFunc func(PostUploaderFilesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUploaderFilesHandlerFunc) Handle(params PostUploaderFilesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostUploaderFilesHandler interface for that can handle valid post uploader files params
type PostUploaderFilesHandler interface {
	Handle(PostUploaderFilesParams, *models.Principal) middleware.Responder
}

// NewPostUploaderFiles creates a new http.Handler for the post uploader files operation
func NewPostUploaderFiles(ctx *middleware.Context, handler PostUploaderFilesHandler) *PostUploaderFiles {
	return &PostUploaderFiles{Context: ctx, Handler: handler}
}

/*
	PostUploaderFiles swagger:route POST /uploader/files uploader postUploaderFiles

Uploads a file.
*/
type PostUploaderFiles struct {
	Context *middleware.Context
	Handler PostUploaderFilesHandler
}

func (o *PostUploaderFiles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUploaderFilesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
