// Code generated by go-swagger; DO NOT EDIT.

package uploader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ole-larsen/uploader/models"
)

// PostUploaderFilesOKCode is the HTTP code returned for type PostUploaderFilesOK
const PostUploaderFilesOKCode int = 200

/*
PostUploaderFilesOK successful upload

swagger:response postUploaderFilesOK
*/
type PostUploaderFilesOK struct {

	/*
	  In: Body
	*/
	Payload *models.PublicFile `json:"body,omitempty"`
}

// NewPostUploaderFilesOK creates PostUploaderFilesOK with default headers values
func NewPostUploaderFilesOK() *PostUploaderFilesOK {

	return &PostUploaderFilesOK{}
}

// WithPayload adds the payload to the post uploader files o k response
func (o *PostUploaderFilesOK) WithPayload(payload *models.PublicFile) *PostUploaderFilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post uploader files o k response
func (o *PostUploaderFilesOK) SetPayload(payload *models.PublicFile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUploaderFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUploaderFilesInternalServerErrorCode is the HTTP code returned for type PostUploaderFilesInternalServerError
const PostUploaderFilesInternalServerErrorCode int = 500

/*
PostUploaderFilesInternalServerError generic error response

swagger:response postUploaderFilesInternalServerError
*/
type PostUploaderFilesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostUploaderFilesInternalServerError creates PostUploaderFilesInternalServerError with default headers values
func NewPostUploaderFilesInternalServerError() *PostUploaderFilesInternalServerError {

	return &PostUploaderFilesInternalServerError{}
}

// WithPayload adds the payload to the post uploader files internal server error response
func (o *PostUploaderFilesInternalServerError) WithPayload(payload *models.Error) *PostUploaderFilesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post uploader files internal server error response
func (o *PostUploaderFilesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUploaderFilesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
