// Code generated by go-swagger; DO NOT EDIT.

package uploader

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/ole-larsen/uploader/models"
)

// PutUploaderFilesHandlerFunc turns a function with the right signature into a put uploader files handler
type PutUploaderFilesHandlerFunc func(PutUploaderFilesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutUploaderFilesHandlerFunc) Handle(params PutUploaderFilesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutUploaderFilesHandler interface for that can handle valid put uploader files params
type PutUploaderFilesHandler interface {
	Handle(PutUploaderFilesParams, *models.Principal) middleware.Responder
}

// NewPutUploaderFiles creates a new http.Handler for the put uploader files operation
func NewPutUploaderFiles(ctx *middleware.Context, handler PutUploaderFilesHandler) *PutUploaderFiles {
	return &PutUploaderFiles{Context: ctx, Handler: handler}
}

/*
	PutUploaderFiles swagger:route PUT /uploader/files uploader putUploaderFiles

Edit uploaded file.
*/
type PutUploaderFiles struct {
	Context *middleware.Context
	Handler PutUploaderFilesHandler
}

func (o *PutUploaderFiles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutUploaderFilesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
