// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ole-larsen/uploader/models"
	"github.com/ole-larsen/uploader/restapi/operations/instruments"
	"github.com/ole-larsen/uploader/restapi/operations/public"
	"github.com/ole-larsen/uploader/restapi/operations/uploader"
)

// NewUploaderAPI creates a new Uploader instance
func NewUploaderAPI(spec *loads.Document) *UploaderAPI {
	return &UploaderAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer:          runtime.JSONConsumer(),
		MultipartformConsumer: runtime.DiscardConsumer,

		JSONProducer: runtime.JSONProducer(),

		PublicGetFilesFileHandler: public.GetFilesFileHandlerFunc(func(params public.GetFilesFileParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetFilesFile has not yet been implemented")
		}),
		InstrumentsGetMetricsHandler: instruments.GetMetricsHandlerFunc(func(params instruments.GetMetricsParams) middleware.Responder {
			return middleware.NotImplemented("operation instruments.GetMetrics has not yet been implemented")
		}),
		PublicGetPingHandler: public.GetPingHandlerFunc(func(params public.GetPingParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation public.GetPing has not yet been implemented")
		}),
		UploaderGetUploaderFilesHandler: uploader.GetUploaderFilesHandlerFunc(func(params uploader.GetUploaderFilesParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation uploader.GetUploaderFiles has not yet been implemented")
		}),
		UploaderGetUploaderFilesIDHandler: uploader.GetUploaderFilesIDHandlerFunc(func(params uploader.GetUploaderFilesIDParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation uploader.GetUploaderFilesID has not yet been implemented")
		}),
		UploaderPostUploaderFilesHandler: uploader.PostUploaderFilesHandlerFunc(func(params uploader.PostUploaderFilesParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation uploader.PostUploaderFiles has not yet been implemented")
		}),
		UploaderPutUploaderFilesHandler: uploader.PutUploaderFilesHandlerFunc(func(params uploader.PutUploaderFilesParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation uploader.PutUploaderFiles has not yet been implemented")
		}),

		// Applies when the "x-token" header is set
		XTokenAuth: func(token string) (*models.Principal, error) {
			return nil, errors.NotImplemented("api key auth (x-token) x-token from header param [x-token] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*UploaderAPI the uploader API */
type UploaderAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer
	// MultipartformConsumer registers a consumer for the following mime types:
	//   - multipart/form-data
	MultipartformConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// XTokenAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key x-token provided in the header
	XTokenAuth func(string) (*models.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// PublicGetFilesFileHandler sets the operation handler for the get files file operation
	PublicGetFilesFileHandler public.GetFilesFileHandler
	// InstrumentsGetMetricsHandler sets the operation handler for the get metrics operation
	InstrumentsGetMetricsHandler instruments.GetMetricsHandler
	// PublicGetPingHandler sets the operation handler for the get ping operation
	PublicGetPingHandler public.GetPingHandler
	// UploaderGetUploaderFilesHandler sets the operation handler for the get uploader files operation
	UploaderGetUploaderFilesHandler uploader.GetUploaderFilesHandler
	// UploaderGetUploaderFilesIDHandler sets the operation handler for the get uploader files ID operation
	UploaderGetUploaderFilesIDHandler uploader.GetUploaderFilesIDHandler
	// UploaderPostUploaderFilesHandler sets the operation handler for the post uploader files operation
	UploaderPostUploaderFilesHandler uploader.PostUploaderFilesHandler
	// UploaderPutUploaderFilesHandler sets the operation handler for the put uploader files operation
	UploaderPutUploaderFilesHandler uploader.PutUploaderFilesHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *UploaderAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *UploaderAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *UploaderAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *UploaderAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *UploaderAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *UploaderAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *UploaderAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *UploaderAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *UploaderAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the UploaderAPI
func (o *UploaderAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}
	if o.MultipartformConsumer == nil {
		unregistered = append(unregistered, "MultipartformConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.XTokenAuth == nil {
		unregistered = append(unregistered, "XTokenAuth")
	}

	if o.PublicGetFilesFileHandler == nil {
		unregistered = append(unregistered, "public.GetFilesFileHandler")
	}
	if o.InstrumentsGetMetricsHandler == nil {
		unregistered = append(unregistered, "instruments.GetMetricsHandler")
	}
	if o.PublicGetPingHandler == nil {
		unregistered = append(unregistered, "public.GetPingHandler")
	}
	if o.UploaderGetUploaderFilesHandler == nil {
		unregistered = append(unregistered, "uploader.GetUploaderFilesHandler")
	}
	if o.UploaderGetUploaderFilesIDHandler == nil {
		unregistered = append(unregistered, "uploader.GetUploaderFilesIDHandler")
	}
	if o.UploaderPostUploaderFilesHandler == nil {
		unregistered = append(unregistered, "uploader.PostUploaderFilesHandler")
	}
	if o.UploaderPutUploaderFilesHandler == nil {
		unregistered = append(unregistered, "uploader.PutUploaderFilesHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *UploaderAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *UploaderAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "x-token":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.XTokenAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *UploaderAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *UploaderAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		case "multipart/form-data":
			result["multipart/form-data"] = o.MultipartformConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *UploaderAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *UploaderAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the uploader API
func (o *UploaderAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *UploaderAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/files/:file"] = public.NewGetFilesFile(o.context, o.PublicGetFilesFileHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/metrics"] = instruments.NewGetMetrics(o.context, o.InstrumentsGetMetricsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/ping"] = public.NewGetPing(o.context, o.PublicGetPingHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/uploader/files"] = uploader.NewGetUploaderFiles(o.context, o.UploaderGetUploaderFilesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/uploader/files/{id}"] = uploader.NewGetUploaderFilesID(o.context, o.UploaderGetUploaderFilesIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/uploader/files"] = uploader.NewPostUploaderFiles(o.context, o.UploaderPostUploaderFilesHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/uploader/files"] = uploader.NewPutUploaderFiles(o.context, o.UploaderPutUploaderFilesHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *UploaderAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *UploaderAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *UploaderAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *UploaderAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *UploaderAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
