// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Uplader Service API
//
//	Schemes:
//	  http
//	Host: uploader
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - multipart/form-data
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
