// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ole-larsen/uploader/models"
)

// GetFilesFileOKCode is the HTTP code returned for type GetFilesFileOK
const GetFilesFileOKCode int = 200

/*
GetFilesFileOK ok

swagger:response getFilesFileOK
*/
type GetFilesFileOK struct {

	/*
	  In: Body
	*/
	Payload models.Uploads `json:"body,omitempty"`
}

// NewGetFilesFileOK creates GetFilesFileOK with default headers values
func NewGetFilesFileOK() *GetFilesFileOK {

	return &GetFilesFileOK{}
}

// WithPayload adds the payload to the get files file o k response
func (o *GetFilesFileOK) WithPayload(payload models.Uploads) *GetFilesFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get files file o k response
func (o *GetFilesFileOK) SetPayload(payload models.Uploads) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFilesFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
