// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFilesFileHandlerFunc turns a function with the right signature into a get files file handler
type GetFilesFileHandlerFunc func(GetFilesFileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFilesFileHandlerFunc) Handle(params GetFilesFileParams) middleware.Responder {
	return fn(params)
}

// GetFilesFileHandler interface for that can handle valid get files file params
type GetFilesFileHandler interface {
	Handle(GetFilesFileParams) middleware.Responder
}

// NewGetFilesFile creates a new http.Handler for the get files file operation
func NewGetFilesFile(ctx *middleware.Context, handler GetFilesFileHandler) *GetFilesFile {
	return &GetFilesFile{Context: ctx, Handler: handler}
}

/*
	GetFilesFile swagger:route GET /files/:file/ public getFilesFile

Serve Static Image
*/
type GetFilesFile struct {
	Context *middleware.Context
	Handler GetFilesFileHandler
}

func (o *GetFilesFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFilesFileParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
