// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ole-larsen/uploader/models"
)

// GetFilesFileOKCode is the HTTP code returned for type GetFilesFileOK
const GetFilesFileOKCode int = 200

/*
GetFilesFileOK ok

swagger:response getFilesFileOK
*/
type GetFilesFileOK struct {

	/*
	  In: Body
	*/
	Payload models.Uploads `json:"body,omitempty"`
}

// NewGetFilesFileOK creates GetFilesFileOK with default headers values
func NewGetFilesFileOK() *GetFilesFileOK {

	return &GetFilesFileOK{}
}

// WithPayload adds the payload to the get files file o k response
func (o *GetFilesFileOK) WithPayload(payload models.Uploads) *GetFilesFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get files file o k response
func (o *GetFilesFileOK) SetPayload(payload models.Uploads) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFilesFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetFilesFileInternalServerErrorCode is the HTTP code returned for type GetFilesFileInternalServerError
const GetFilesFileInternalServerErrorCode int = 500

/*
GetFilesFileInternalServerError generic error response

swagger:response getFilesFileInternalServerError
*/
type GetFilesFileInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFilesFileInternalServerError creates GetFilesFileInternalServerError with default headers values
func NewGetFilesFileInternalServerError() *GetFilesFileInternalServerError {

	return &GetFilesFileInternalServerError{}
}

// WithPayload adds the payload to the get files file internal server error response
func (o *GetFilesFileInternalServerError) WithPayload(payload *models.Error) *GetFilesFileInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get files file internal server error response
func (o *GetFilesFileInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFilesFileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
