name: Provider CI/CD
run-name: ${{ github.actor }} is starting GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: setup Go environment
        uses: actions/setup-go@v3.4.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: |
          go version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPO }}:latest
