// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Metrics metrics
//
// swagger:model metrics
type Metrics map[string]float64

// Validate validates this metrics
func (m Metrics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metrics based on context it is used
func (m Metrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
