// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Uploads uploads
//
// swagger:model uploads
type Uploads string

// Validate validates this uploads
func (m Uploads) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this uploads based on context it is used
func (m Uploads) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
